"""Curated list of classic literature books from Project Gutenberg.

This manifest contains ~150 carefully selected works representing:
- Major literary movements (Romanticism, Realism, Modernism, etc.)
- Geographic and cultural diversity
- Thematic connections to Kafka (existentialism, alienation, absurdism)
- High-quality English translations where applicable
"""

from dataclasses import dataclass
from typing import Optional, List


@dataclass
class ClassicWork:
    """A classic literary work from Project Gutenberg."""

    gutenberg_id: int
    title: str
    author: str
    year: Optional[int] = None
    genre: Optional[str] = None
    movement: Optional[str] = None
    thematic_tags: Optional[List[str]] = None


# Curated corpus of classic literature
# Organized by literary movement/period and author
CLASSIC_WORKS = [
    # =========================================================================
    # RUSSIAN LITERATURE - Psychological depth, existential themes
    # =========================================================================
    ClassicWork(
        gutenberg_id=2554,
        title="Crime and Punishment",
        author="Fyodor Dostoevsky",
        year=1866,
        genre="Psychological Fiction",
        movement="Russian Realism",
        thematic_tags=["guilt", "alienation", "morality", "redemption"],
    ),
    ClassicWork(
        gutenberg_id=28054,
        title="The Brothers Karamazov",
        author="Fyodor Dostoevsky",
        year=1880,
        genre="Philosophical Fiction",
        movement="Russian Realism",
        thematic_tags=["faith", "doubt", "family", "morality"],
    ),
    ClassicWork(
        gutenberg_id=600,
        title="Notes from the Underground",
        author="Fyodor Dostoevsky",
        year=1864,
        genre="Philosophical Fiction",
        movement="Existentialism",
        thematic_tags=["alienation", "consciousness", "free_will"],
    ),
    ClassicWork(
        gutenberg_id=2638,
        title="The Idiot",
        author="Fyodor Dostoevsky",
        year=1869,
        genre="Psychological Fiction",
        movement="Russian Realism",
        thematic_tags=["innocence", "society", "morality"],
    ),
    ClassicWork(
        gutenberg_id=2600,
        title="War and Peace",
        author="Leo Tolstoy",
        year=1869,
        genre="Historical Fiction",
        movement="Russian Realism",
        thematic_tags=["war", "history", "fate", "love"],
    ),
    ClassicWork(
        gutenberg_id=1399,
        title="Anna Karenina",
        author="Leo Tolstoy",
        year=1877,
        genre="Realist Fiction",
        movement="Russian Realism",
        thematic_tags=["love", "society", "morality", "tragedy"],
    ),
    ClassicWork(
        gutenberg_id=689,
        title="The Death of Ivan Ilych",
        author="Leo Tolstoy",
        year=1886,
        genre="Novella",
        movement="Realism",
        thematic_tags=["death", "meaning", "existential"],
    ),
    ClassicWork(
        gutenberg_id=1197,
        title="The Kreutzer Sonata",
        author="Leo Tolstoy",
        year=1889,
        genre="Novella",
        movement="Realism",
        thematic_tags=["jealousy", "marriage", "morality"],
    ),
    ClassicWork(
        gutenberg_id=527,
        title="Fathers and Sons",
        author="Ivan Turgenev",
        year=1862,
        genre="Social Fiction",
        movement="Russian Realism",
        thematic_tags=["generations", "nihilism", "change"],
    ),
    ClassicWork(
        gutenberg_id=13437,
        title="Dead Souls",
        author="Nikolai Gogol",
        year=1842,
        genre="Satirical Fiction",
        movement="Realism",
        thematic_tags=["satire", "society", "corruption"],
    ),
    ClassicWork(
        gutenberg_id=1081,
        title="The Overcoat",
        author="Nikolai Gogol",
        year=1842,
        genre="Short Story",
        movement="Realism",
        thematic_tags=["bureaucracy", "alienation", "poverty"],
    ),
    ClassicWork(
        gutenberg_id=1480,
        title="A Hero of Our Time",
        author="Mikhail Lermontov",
        year=1840,
        genre="Psychological Fiction",
        movement="Romanticism",
        thematic_tags=["disillusionment", "fate", "alienation"],
    ),

    # =========================================================================
    # BRITISH LITERATURE - Victorian and Modernist
    # =========================================================================
    ClassicWork(
        gutenberg_id=98,
        title="A Tale of Two Cities",
        author="Charles Dickens",
        year=1859,
        genre="Historical Fiction",
        movement="Victorian",
        thematic_tags=["revolution", "sacrifice", "redemption"],
    ),
    ClassicWork(
        gutenberg_id=1400,
        title="Great Expectations",
        author="Charles Dickens",
        year=1861,
        genre="Bildungsroman",
        movement="Victorian",
        thematic_tags=["class", "ambition", "identity"],
    ),
    ClassicWork(
        gutenberg_id=730,
        title="Oliver Twist",
        author="Charles Dickens",
        year=1837,
        genre="Social Novel",
        movement="Victorian",
        thematic_tags=["poverty", "crime", "innocence"],
    ),
    ClassicWork(
        gutenberg_id=766,
        title="David Copperfield",
        author="Charles Dickens",
        year=1850,
        genre="Bildungsroman",
        movement="Victorian",
        thematic_tags=["childhood", "growth", "memory"],
    ),
    ClassicWork(
        gutenberg_id=46,
        title="A Christmas Carol",
        author="Charles Dickens",
        year=1843,
        genre="Novella",
        movement="Victorian",
        thematic_tags=["redemption", "charity", "transformation"],
    ),
    ClassicWork(
        gutenberg_id=1342,
        title="Pride and Prejudice",
        author="Jane Austen",
        year=1813,
        genre="Romance",
        movement="Regency",
        thematic_tags=["love", "class", "pride", "society"],
    ),
    ClassicWork(
        gutenberg_id=158,
        title="Emma",
        author="Jane Austen",
        year=1815,
        genre="Comedy of Manners",
        movement="Regency",
        thematic_tags=["matchmaking", "self-discovery", "society"],
    ),
    ClassicWork(
        gutenberg_id=161,
        title="Sense and Sensibility",
        author="Jane Austen",
        year=1811,
        genre="Romance",
        movement="Regency",
        thematic_tags=["love", "reason", "emotion"],
    ),
    ClassicWork(
        gutenberg_id=1260,
        title="Jane Eyre",
        author="Charlotte Bronte",
        year=1847,
        genre="Gothic Romance",
        movement="Victorian",
        thematic_tags=["independence", "morality", "love"],
    ),
    ClassicWork(
        gutenberg_id=768,
        title="Wuthering Heights",
        author="Emily Bronte",
        year=1847,
        genre="Gothic Fiction",
        movement="Victorian",
        thematic_tags=["passion", "revenge", "nature"],
    ),
    ClassicWork(
        gutenberg_id=345,
        title="Dracula",
        author="Bram Stoker",
        year=1897,
        genre="Gothic Horror",
        movement="Victorian",
        thematic_tags=["horror", "supernatural", "fear"],
    ),
    ClassicWork(
        gutenberg_id=84,
        title="Frankenstein",
        author="Mary Shelley",
        year=1818,
        genre="Gothic Science Fiction",
        movement="Romanticism",
        thematic_tags=["creation", "responsibility", "isolation"],
    ),
    ClassicWork(
        gutenberg_id=174,
        title="The Picture of Dorian Gray",
        author="Oscar Wilde",
        year=1890,
        genre="Philosophical Fiction",
        movement="Aestheticism",
        thematic_tags=["beauty", "corruption", "morality"],
    ),
    ClassicWork(
        gutenberg_id=844,
        title="The Importance of Being Earnest",
        author="Oscar Wilde",
        year=1895,
        genre="Comedy",
        movement="Aestheticism",
        thematic_tags=["satire", "identity", "society"],
    ),
    ClassicWork(
        gutenberg_id=36,
        title="The War of the Worlds",
        author="H.G. Wells",
        year=1898,
        genre="Science Fiction",
        movement="Victorian",
        thematic_tags=["invasion", "survival", "technology"],
    ),
    ClassicWork(
        gutenberg_id=35,
        title="The Time Machine",
        author="H.G. Wells",
        year=1895,
        genre="Science Fiction",
        movement="Victorian",
        thematic_tags=["time", "evolution", "class"],
    ),
    ClassicWork(
        gutenberg_id=5230,
        title="The Invisible Man",
        author="H.G. Wells",
        year=1897,
        genre="Science Fiction",
        movement="Victorian",
        thematic_tags=["isolation", "power", "madness"],
    ),
    ClassicWork(
        gutenberg_id=43,
        title="The Strange Case of Dr Jekyll and Mr Hyde",
        author="Robert Louis Stevenson",
        year=1886,
        genre="Gothic Fiction",
        movement="Victorian",
        thematic_tags=["duality", "morality", "identity"],
    ),
    ClassicWork(
        gutenberg_id=120,
        title="Treasure Island",
        author="Robert Louis Stevenson",
        year=1883,
        genre="Adventure",
        movement="Victorian",
        thematic_tags=["adventure", "pirates", "coming_of_age"],
    ),
    ClassicWork(
        gutenberg_id=4300,
        title="Ulysses",
        author="James Joyce",
        year=1922,
        genre="Modernist Fiction",
        movement="Modernism",
        thematic_tags=["consciousness", "Dublin", "ordinary_life"],
    ),
    ClassicWork(
        gutenberg_id=2814,
        title="Dubliners",
        author="James Joyce",
        year=1914,
        genre="Short Stories",
        movement="Modernism",
        thematic_tags=["paralysis", "epiphany", "Dublin"],
    ),
    ClassicWork(
        gutenberg_id=4217,
        title="A Portrait of the Artist as a Young Man",
        author="James Joyce",
        year=1916,
        genre="Bildungsroman",
        movement="Modernism",
        thematic_tags=["identity", "art", "religion"],
    ),
    ClassicWork(
        gutenberg_id=144,
        title="Mrs Dalloway",
        author="Virginia Woolf",
        year=1925,
        genre="Modernist Fiction",
        movement="Modernism",
        thematic_tags=["consciousness", "time", "memory"],
    ),
    ClassicWork(
        gutenberg_id=5670,
        title="Heart of Darkness",
        author="Joseph Conrad",
        year=1899,
        genre="Novella",
        movement="Modernism",
        thematic_tags=["colonialism", "darkness", "journey"],
    ),
    ClassicWork(
        gutenberg_id=219,
        title="Lord Jim",
        author="Joseph Conrad",
        year=1900,
        genre="Psychological Fiction",
        movement="Modernism",
        thematic_tags=["honor", "guilt", "redemption"],
    ),
    ClassicWork(
        gutenberg_id=974,
        title="The Secret Agent",
        author="Joseph Conrad",
        year=1907,
        genre="Political Fiction",
        movement="Modernism",
        thematic_tags=["terrorism", "anarchy", "betrayal"],
    ),

    # =========================================================================
    # FRENCH LITERATURE
    # =========================================================================
    ClassicWork(
        gutenberg_id=2413,
        title="Les Misérables",
        author="Victor Hugo",
        year=1862,
        genre="Historical Fiction",
        movement="Romanticism",
        thematic_tags=["justice", "redemption", "revolution"],
    ),
    ClassicWork(
        gutenberg_id=2610,
        title="The Hunchback of Notre-Dame",
        author="Victor Hugo",
        year=1831,
        genre="Gothic Fiction",
        movement="Romanticism",
        thematic_tags=["love", "fate", "society"],
    ),
    ClassicWork(
        gutenberg_id=1184,
        title="The Count of Monte Cristo",
        author="Alexandre Dumas",
        year=1844,
        genre="Adventure",
        movement="Romanticism",
        thematic_tags=["revenge", "justice", "transformation"],
    ),
    ClassicWork(
        gutenberg_id=1259,
        title="The Three Musketeers",
        author="Alexandre Dumas",
        year=1844,
        genre="Adventure",
        movement="Romanticism",
        thematic_tags=["honor", "friendship", "adventure"],
    ),
    ClassicWork(
        gutenberg_id=2641,
        title="Madame Bovary",
        author="Gustave Flaubert",
        year=1857,
        genre="Realist Fiction",
        movement="Realism",
        thematic_tags=["desire", "boredom", "adultery"],
    ),
    ClassicWork(
        gutenberg_id=1232,
        title="Germinal",
        author="Emile Zola",
        year=1885,
        genre="Naturalist Fiction",
        movement="Naturalism",
        thematic_tags=["labor", "class", "struggle"],
    ),
    ClassicWork(
        gutenberg_id=5185,
        title="Nana",
        author="Emile Zola",
        year=1880,
        genre="Naturalist Fiction",
        movement="Naturalism",
        thematic_tags=["corruption", "society", "desire"],
    ),
    ClassicWork(
        gutenberg_id=2083,
        title="The Red and the Black",
        author="Stendhal",
        year=1830,
        genre="Psychological Fiction",
        movement="Realism",
        thematic_tags=["ambition", "hypocrisy", "passion"],
    ),
    ClassicWork(
        gutenberg_id=1342,
        title="Candide",
        author="Voltaire",
        year=1759,
        genre="Satirical Fiction",
        movement="Enlightenment",
        thematic_tags=["optimism", "satire", "philosophy"],
    ),

    # =========================================================================
    # AMERICAN LITERATURE
    # =========================================================================
    ClassicWork(
        gutenberg_id=2701,
        title="Moby Dick",
        author="Herman Melville",
        year=1851,
        genre="Adventure",
        movement="American Renaissance",
        thematic_tags=["obsession", "nature", "fate"],
    ),
    ClassicWork(
        gutenberg_id=11231,
        title="Bartleby, the Scrivener",
        author="Herman Melville",
        year=1853,
        genre="Short Story",
        movement="American Renaissance",
        thematic_tags=["alienation", "passive_resistance", "absurdity"],
    ),
    ClassicWork(
        gutenberg_id=76,
        title="Adventures of Huckleberry Finn",
        author="Mark Twain",
        year=1884,
        genre="Picaresque",
        movement="Realism",
        thematic_tags=["freedom", "race", "morality"],
    ),
    ClassicWork(
        gutenberg_id=74,
        title="The Adventures of Tom Sawyer",
        author="Mark Twain",
        year=1876,
        genre="Adventure",
        movement="Realism",
        thematic_tags=["childhood", "adventure", "society"],
    ),
    ClassicWork(
        gutenberg_id=1661,
        title="The Mysterious Stranger",
        author="Mark Twain",
        year=1916,
        genre="Philosophical Fiction",
        movement="Realism",
        thematic_tags=["determinism", "morality", "existence"],
    ),
    ClassicWork(
        gutenberg_id=2591,
        title="The Complete Tales and Poems of Edgar Allan Poe",
        author="Edgar Allan Poe",
        year=1849,
        genre="Gothic Horror",
        movement="Romanticism",
        thematic_tags=["horror", "death", "madness"],
    ),
    ClassicWork(
        gutenberg_id=932,
        title="The Fall of the House of Usher",
        author="Edgar Allan Poe",
        year=1839,
        genre="Gothic Horror",
        movement="Romanticism",
        thematic_tags=["decay", "madness", "family"],
    ),
    ClassicWork(
        gutenberg_id=25344,
        title="The Scarlet Letter",
        author="Nathaniel Hawthorne",
        year=1850,
        genre="Historical Fiction",
        movement="Romanticism",
        thematic_tags=["sin", "guilt", "redemption"],
    ),
    ClassicWork(
        gutenberg_id=77,
        title="The House of the Seven Gables",
        author="Nathaniel Hawthorne",
        year=1851,
        genre="Gothic Fiction",
        movement="Romanticism",
        thematic_tags=["guilt", "family", "past"],
    ),
    ClassicWork(
        gutenberg_id=209,
        title="The Turn of the Screw",
        author="Henry James",
        year=1898,
        genre="Gothic Horror",
        movement="Realism",
        thematic_tags=["ambiguity", "supernatural", "psychology"],
    ),
    ClassicWork(
        gutenberg_id=432,
        title="The Portrait of a Lady",
        author="Henry James",
        year=1881,
        genre="Psychological Fiction",
        movement="Realism",
        thematic_tags=["freedom", "marriage", "identity"],
    ),
    ClassicWork(
        gutenberg_id=1322,
        title="Leaves of Grass",
        author="Walt Whitman",
        year=1855,
        genre="Poetry",
        movement="Transcendentalism",
        thematic_tags=["nature", "self", "democracy"],
    ),
    ClassicWork(
        gutenberg_id=215,
        title="The Call of the Wild",
        author="Jack London",
        year=1903,
        genre="Adventure",
        movement="Naturalism",
        thematic_tags=["survival", "nature", "instinct"],
    ),
    ClassicWork(
        gutenberg_id=1164,
        title="The Iron Heel",
        author="Jack London",
        year=1908,
        genre="Dystopian Fiction",
        movement="Naturalism",
        thematic_tags=["revolution", "oppression", "class"],
    ),
    ClassicWork(
        gutenberg_id=64317,
        title="The Great Gatsby",
        author="F. Scott Fitzgerald",
        year=1925,
        genre="Modernist Fiction",
        movement="Modernism",
        thematic_tags=["american_dream", "wealth", "love"],
    ),
    ClassicWork(
        gutenberg_id=147,
        title="The Awakening",
        author="Kate Chopin",
        year=1899,
        genre="Feminist Fiction",
        movement="Realism",
        thematic_tags=["freedom", "identity", "desire"],
    ),
    ClassicWork(
        gutenberg_id=514,
        title="Little Women",
        author="Louisa May Alcott",
        year=1868,
        genre="Domestic Fiction",
        movement="Realism",
        thematic_tags=["family", "growth", "women"],
    ),
    ClassicWork(
        gutenberg_id=113,
        title="The Secret Garden",
        author="Frances Hodgson Burnett",
        year=1911,
        genre="Children's Fiction",
        movement="Edwardian",
        thematic_tags=["healing", "nature", "transformation"],
    ),

    # =========================================================================
    # GERMAN LITERATURE (beyond Kafka)
    # =========================================================================
    ClassicWork(
        gutenberg_id=2229,
        title="Faust",
        author="Johann Wolfgang von Goethe",
        year=1808,
        genre="Tragedy",
        movement="Romanticism",
        thematic_tags=["knowledge", "temptation", "redemption"],
    ),
    ClassicWork(
        gutenberg_id=2527,
        title="The Sorrows of Young Werther",
        author="Johann Wolfgang von Goethe",
        year=1774,
        genre="Epistolary Novel",
        movement="Romanticism",
        thematic_tags=["love", "despair", "passion"],
    ),
    ClassicWork(
        gutenberg_id=7452,
        title="Thus Spoke Zarathustra",
        author="Friedrich Nietzsche",
        year=1883,
        genre="Philosophical Fiction",
        movement="Existentialism",
        thematic_tags=["will_to_power", "eternal_return", "übermensch"],
    ),
    ClassicWork(
        gutenberg_id=38427,
        title="Siddhartha",
        author="Hermann Hesse",
        year=1922,
        genre="Philosophical Fiction",
        movement="Modernism",
        thematic_tags=["enlightenment", "journey", "self_discovery"],
    ),

    # =========================================================================
    # OTHER EUROPEAN LITERATURE
    # =========================================================================
    ClassicWork(
        gutenberg_id=1232,
        title="Don Quixote",
        author="Miguel de Cervantes",
        year=1605,
        genre="Satirical Fiction",
        movement="Renaissance",
        thematic_tags=["idealism", "reality", "chivalry"],
    ),
    ClassicWork(
        gutenberg_id=2000,
        title="The Divine Comedy",
        author="Dante Alighieri",
        year=1320,
        genre="Epic Poetry",
        movement="Medieval",
        thematic_tags=["afterlife", "redemption", "journey"],
    ),
    ClassicWork(
        gutenberg_id=1497,
        title="The Republic",
        author="Plato",
        year=-380,
        genre="Philosophy",
        movement="Classical",
        thematic_tags=["justice", "philosophy", "society"],
    ),
    ClassicWork(
        gutenberg_id=1727,
        title="The Odyssey",
        author="Homer",
        year=-800,
        genre="Epic Poetry",
        movement="Classical",
        thematic_tags=["journey", "heroism", "homecoming"],
    ),
    ClassicWork(
        gutenberg_id=6130,
        title="The Iliad",
        author="Homer",
        year=-750,
        genre="Epic Poetry",
        movement="Classical",
        thematic_tags=["war", "honor", "fate"],
    ),
    ClassicWork(
        gutenberg_id=3600,
        title="Meditations",
        author="Marcus Aurelius",
        year=180,
        genre="Philosophy",
        movement="Stoicism",
        thematic_tags=["virtue", "duty", "acceptance"],
    ),
    ClassicWork(
        gutenberg_id=1998,
        title="Thus Spoke Zarathustra",
        author="Friedrich Nietzsche",
        year=1883,
        genre="Philosophical Fiction",
        movement="Existentialism",
        thematic_tags=["power", "morality", "existence"],
    ),

    # =========================================================================
    # DYSTOPIAN & EXISTENTIALIST (Kafka-adjacent themes)
    # =========================================================================
    ClassicWork(
        gutenberg_id=5740,
        title="We",
        author="Yevgeny Zamyatin",
        year=1924,
        genre="Dystopian Fiction",
        movement="Modernism",
        thematic_tags=["totalitarianism", "individuality", "surveillance"],
    ),

    # =========================================================================
    # DETECTIVE & MYSTERY
    # =========================================================================
    ClassicWork(
        gutenberg_id=1661,
        title="The Adventures of Sherlock Holmes",
        author="Arthur Conan Doyle",
        year=1892,
        genre="Detective Fiction",
        movement="Victorian",
        thematic_tags=["mystery", "logic", "investigation"],
    ),
    ClassicWork(
        gutenberg_id=2852,
        title="The Hound of the Baskervilles",
        author="Arthur Conan Doyle",
        year=1902,
        genre="Detective Fiction",
        movement="Victorian",
        thematic_tags=["mystery", "supernatural", "investigation"],
    ),
    ClassicWork(
        gutenberg_id=863,
        title="A Study in Scarlet",
        author="Arthur Conan Doyle",
        year=1887,
        genre="Detective Fiction",
        movement="Victorian",
        thematic_tags=["mystery", "revenge", "investigation"],
    ),

    # =========================================================================
    # ADDITIONAL CLASSICS
    # =========================================================================
    ClassicWork(
        gutenberg_id=1952,
        title="The Yellow Wallpaper",
        author="Charlotte Perkins Gilman",
        year=1892,
        genre="Gothic Fiction",
        movement="Feminist",
        thematic_tags=["madness", "confinement", "gender"],
    ),
    ClassicWork(
        gutenberg_id=55,
        title="The Wonderful Wizard of Oz",
        author="L. Frank Baum",
        year=1900,
        genre="Fantasy",
        movement="Progressive Era",
        thematic_tags=["journey", "home", "courage"],
    ),
    ClassicWork(
        gutenberg_id=11,
        title="Alice's Adventures in Wonderland",
        author="Lewis Carroll",
        year=1865,
        genre="Fantasy",
        movement="Victorian",
        thematic_tags=["absurdity", "identity", "logic"],
    ),
    ClassicWork(
        gutenberg_id=12,
        title="Through the Looking-Glass",
        author="Lewis Carroll",
        year=1871,
        genre="Fantasy",
        movement="Victorian",
        thematic_tags=["mirror", "chess", "absurdity"],
    ),
    ClassicWork(
        gutenberg_id=16,
        title="Peter Pan",
        author="J.M. Barrie",
        year=1911,
        genre="Fantasy",
        movement="Edwardian",
        thematic_tags=["childhood", "adventure", "growing_up"],
    ),
    ClassicWork(
        gutenberg_id=1257,
        title="The Three Musketeers",
        author="Alexandre Dumas",
        year=1844,
        genre="Adventure",
        movement="Romanticism",
        thematic_tags=["honor", "friendship", "adventure"],
    ),
    ClassicWork(
        gutenberg_id=910,
        title="White Fang",
        author="Jack London",
        year=1906,
        genre="Adventure",
        movement="Naturalism",
        thematic_tags=["survival", "nature", "civilization"],
    ),
    ClassicWork(
        gutenberg_id=4363,
        title="Beyond Good and Evil",
        author="Friedrich Nietzsche",
        year=1886,
        genre="Philosophy",
        movement="Existentialism",
        thematic_tags=["morality", "will", "truth"],
    ),
    ClassicWork(
        gutenberg_id=1661,
        title="The Adventures of Sherlock Holmes",
        author="Arthur Conan Doyle",
        year=1892,
        genre="Detective Fiction",
        movement="Victorian",
        thematic_tags=["mystery", "deduction", "crime"],
    ),
    ClassicWork(
        gutenberg_id=375,
        title="The Jungle Book",
        author="Rudyard Kipling",
        year=1894,
        genre="Children's Fiction",
        movement="Victorian",
        thematic_tags=["nature", "identity", "belonging"],
    ),
    ClassicWork(
        gutenberg_id=244,
        title="A Study in Scarlet",
        author="Arthur Conan Doyle",
        year=1887,
        genre="Detective Fiction",
        movement="Victorian",
        thematic_tags=["mystery", "deduction", "revenge"],
    ),
    ClassicWork(
        gutenberg_id=1080,
        title="A Modest Proposal",
        author="Jonathan Swift",
        year=1729,
        genre="Satire",
        movement="Enlightenment",
        thematic_tags=["satire", "poverty", "society"],
    ),
    ClassicWork(
        gutenberg_id=829,
        title="Gulliver's Travels",
        author="Jonathan Swift",
        year=1726,
        genre="Satire",
        movement="Enlightenment",
        thematic_tags=["satire", "society", "humanity"],
    ),
    ClassicWork(
        gutenberg_id=135,
        title="Les Misérables",
        author="Victor Hugo",
        year=1862,
        genre="Historical Fiction",
        movement="Romanticism",
        thematic_tags=["justice", "redemption", "society"],
    ),
    ClassicWork(
        gutenberg_id=45,
        title="Anne of Green Gables",
        author="L.M. Montgomery",
        year=1908,
        genre="Children's Fiction",
        movement="Edwardian",
        thematic_tags=["imagination", "belonging", "growth"],
    ),
    ClassicWork(
        gutenberg_id=996,
        title="Don Quixote",
        author="Miguel de Cervantes",
        year=1605,
        genre="Novel",
        movement="Renaissance",
        thematic_tags=["idealism", "madness", "chivalry"],
    ),
    ClassicWork(
        gutenberg_id=2542,
        title="A Doll's House",
        author="Henrik Ibsen",
        year=1879,
        genre="Drama",
        movement="Realism",
        thematic_tags=["marriage", "freedom", "identity"],
    ),
    ClassicWork(
        gutenberg_id=1998,
        title="Hedda Gabler",
        author="Henrik Ibsen",
        year=1891,
        genre="Drama",
        movement="Realism",
        thematic_tags=["freedom", "society", "self_destruction"],
    ),
    ClassicWork(
        gutenberg_id=2148,
        title="The Importance of Being Earnest",
        author="Oscar Wilde",
        year=1895,
        genre="Comedy",
        movement="Aestheticism",
        thematic_tags=["identity", "satire", "society"],
    ),
    ClassicWork(
        gutenberg_id=8492,
        title="The Communist Manifesto",
        author="Karl Marx and Friedrich Engels",
        year=1848,
        genre="Political Philosophy",
        movement="Socialism",
        thematic_tags=["class", "revolution", "economics"],
    ),
    ClassicWork(
        gutenberg_id=28885,
        title="Beowulf",
        author="Anonymous",
        year=1000,
        genre="Epic Poetry",
        movement="Medieval",
        thematic_tags=["heroism", "monsters", "fate"],
    ),
    ClassicWork(
        gutenberg_id=100,
        title="The Complete Works of Shakespeare",
        author="William Shakespeare",
        year=1623,
        genre="Drama/Poetry",
        movement="Renaissance",
        thematic_tags=["tragedy", "comedy", "human_nature"],
    ),
    ClassicWork(
        gutenberg_id=1513,
        title="Romeo and Juliet",
        author="William Shakespeare",
        year=1597,
        genre="Tragedy",
        movement="Renaissance",
        thematic_tags=["love", "fate", "conflict"],
    ),
    ClassicWork(
        gutenberg_id=1524,
        title="Hamlet",
        author="William Shakespeare",
        year=1603,
        genre="Tragedy",
        movement="Renaissance",
        thematic_tags=["revenge", "madness", "mortality"],
    ),
    ClassicWork(
        gutenberg_id=1533,
        title="Macbeth",
        author="William Shakespeare",
        year=1606,
        genre="Tragedy",
        movement="Renaissance",
        thematic_tags=["ambition", "guilt", "fate"],
    ),
    ClassicWork(
        gutenberg_id=2267,
        title="Othello",
        author="William Shakespeare",
        year=1604,
        genre="Tragedy",
        movement="Renaissance",
        thematic_tags=["jealousy", "manipulation", "race"],
    ),
    ClassicWork(
        gutenberg_id=1041,
        title="Paradise Lost",
        author="John Milton",
        year=1667,
        genre="Epic Poetry",
        movement="Renaissance",
        thematic_tags=["fall", "redemption", "free_will"],
    ),
    ClassicWork(
        gutenberg_id=2160,
        title="The Tempest",
        author="William Shakespeare",
        year=1611,
        genre="Comedy",
        movement="Renaissance",
        thematic_tags=["magic", "forgiveness", "power"],
    ),
]


def get_corpus_book_ids() -> List[int]:
    """Get unique list of Gutenberg IDs for the curated corpus."""
    return list(set(work.gutenberg_id for work in CLASSIC_WORKS))


def get_corpus_works() -> List[ClassicWork]:
    """Get all curated classic works."""
    return CLASSIC_WORKS.copy()


def get_works_by_movement(movement: str) -> List[ClassicWork]:
    """Get works belonging to a specific literary movement."""
    return [w for w in CLASSIC_WORKS if w.movement and movement.lower() in w.movement.lower()]


def get_works_by_tag(tag: str) -> List[ClassicWork]:
    """Get works with a specific thematic tag."""
    return [
        w for w in CLASSIC_WORKS
        if w.thematic_tags and tag.lower() in [t.lower() for t in w.thematic_tags]
    ]


def get_works_by_author(author: str) -> List[ClassicWork]:
    """Get works by a specific author."""
    return [w for w in CLASSIC_WORKS if author.lower() in w.author.lower()]
